
/* This file is automatically generated -- DO NOT EDIT! */

package com.stormwyrm.nekoarc.ciel;

import com.stormwyrm.nekoarc.types.OutputPort;

public enum CAsm {
    GNIL(0x0),
    GTRUE(0x8),
    LAST(0xff);

    /**
     * The opcode for the instruction
     */
    private final byte opcode;

    /**
     * Create a new opcode for an instruction. Default to no arguments.
     * @param opcode The opcode
     */
    CAsm(int opcode) {
        this.opcode = (byte) opcode;
    }

    /**
     * Get the opcode for the instruction.
     * @return the opcode value
     */
    public byte opcode() {
        return(this.opcode);
    }

    /**
     * Emit code for the opcode
     * @param fp The output port to send the opcode to
     */
    void emit(OutputPort fp) {
        fp.writeb(opcode);
    }
}
